### ISSUE TITLE
move adaptor fa file to common location

### ISSUE THREAD

**Issue by slsevilla** [CCBR/MAPLE#2]
Need to move the fa file for adaptor trimming to a common location. @kopardev where should we keep these?

```
cutadapt -j 32 -b file:TruSeq_and_nextera_adapters.fa -B file:TruSeq_and_nextera_adapters.fa --trim-n -m 50 -o ${output}_R1.trimmed.fastq.gz -p ${output}_R2.trimmed.fastq.gz ${path}/${R1} ${path}/${R2}
```

**Comment by slsevilla** [comment]
use CCBR_Pipeliner location

**Comment by wilfriedguiblet** [comment]
Don't have the permission to write in `/data/CCBR_Pipeliner/`

Copied `TruSeq_and_nextera_adapters.fa` into `/data/CCBR/rawdata/ccbr1214/`

**Comment by slsevilla** [comment]
Thanks! I'll move them into the dir.

**Comment by slsevilla** [comment]
Completed. Adaptors here: /data/CCBR_Pipeliner/ccbr1214/adapters/
