### ISSUE TITLE
make switch if 'select bed' is given

### ISSUE THREAD

**Issue by slsevilla** [CCBR/MAPLE#3]
@wilfriedguiblet  - question

for this optional command:
```
## OPTIONAL ###########
# bedtools -a ${output}.mapped.hg19.bed -b intervals_of_interests.bed > ${output}.selected.hg19.bed
# awk '{ if ($3-$2 >= 140 && $3-$2 <= 160) print $0}' ${output}.selected.hg19.bed > ${output}.selected.hg19.140-160.bed 
```

If this is selected, would you also create a histogram for the bed file? I'm imagining that the first pass would include the "everything.bed" and then a second pass would include the "selected.bed". Is that right?

**Comment by wilfriedguiblet** [comment]
Not 100% sure I understand the question.

Part I: Histogram of length should be computed with all fragments. No selection.

Part II: Histogram of DYADs (or occurrences), should be computed with `${output}.selected.hg19.${length}.bed`

**Comment by slsevilla** [comment]
I'm trying to iron out how this file fits in... I think there are three scenarios: 
1) will we always have a "intervals_of_interest" bed file at the start of the pipeline 
2) sometimes we'll have it, and other times we won't 
3) we'll never have it at the start of the pipeline, only after we've run part of the pipeline

Scenario 1.
--Required input: intervals_of_interest --
Rule make_bed
Rule make_histograms from output of make_bed
Rule make_selected_bed
Rule make_histograms from output of selected_bed

Scenario 2.
--Optional input: intervals_of_interest --
Rule make_bed
Rule make_histograms from output of make_bed
Optional Rule make_selected_bed
Optional Rule make_histograms from output of selected_bed

Scenario 3.
Rule make_bed
Rule make_histograms from output of make_bed
--Review data; Create intervals_of_interest --
Rule make_selected_bed
Rule make_histograms from output of selected_bed

**Comment by wilfriedguiblet** [comment]
I understand. Here is what I for-see:

Part I will need to run only the 1 time.
Part II will need to run multiple times, with different combinations of intervals and fragments lengths.

Fragment lengths will always be used (default should be [140-160]).
Intervals will be optional.

**Comment by slsevilla** [comment]
Added line to the config file for users to determine whether to create selected_bed and to provide bed file OR to skip this step
